language: cpp
before_script:
- sudo apt update
- sudo apt install libboost-all-dev libgtest-dev cmake -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list.d/xenial.list
- cd /usr/src/gtest
- sudo cmake .
- sudo cmake --build .
- sudo cp *.a /usr/lib
- cd ${TRAVIS_BUILD_DIR}
- sudo apt update
script:
- cmake .
- cmake --build .
  #- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -unazdryuhin:$BINTRAY_API_KEY "https://api.bintray.com/content/nazdryuhin/HomeWork/hw02/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
